stages:
  collect_data:
    cmd: python src/data/collect_data.py --out data/raw/sms.csv
    outs:
      - data/raw/sms.csv

  preprocess:
    cmd: python src/data/preprocess.py --in data/raw/sms.csv --out data/processed/sms_clean.csv
    deps:
      - src/data/preprocess.py
      - data/raw/sms.csv
    outs:
      - data/processed/sms_clean.csv

  train:
    cmd: python src/models/train.py --data data/processed/sms_clean.csv --out models/model.pkl
    deps:
      - src/models/train.py
      - data/processed/sms_clean.csv
    outs:
      - models/model.pkl

  evaluate:
    cmd: python src/models/evaluate.py --model models/model.pkl --data data/processed/sms_clean.csv --out reports/metrics.json
    deps:
      - src/models/evaluate.py
      - models/model.pkl
      - data/processed/sms_clean.csv
    outs:
      - reports/metrics.json
