# dvc.yaml - Version simplifiée sans params
vars:
  - data_path: "data/raw/sms.csv"
  - processed_path: "data/processed/sms_clean.csv"

stages:
  collect_data:
    cmd: python src/data/collect_data.py --out ${data_path}
    outs:
      - ${data_path}

  preprocess:
    cmd: python src/data/preprocess.py --in ${data_path} --out ${processed_path}
    deps:
      - src/data/preprocess.py
      - ${data_path}
    outs:
      - ${processed_path}

  train_logistic:
    cmd: python src/models/train.py --data ${processed_path} --out models/model_logistic.pkl --model_type logistic
    deps:
      - src/models/train.py
      - ${processed_path}
    outs:
      - models/model_logistic.pkl

  train_svm:
    cmd: python src/models/train.py --data ${processed_path} --out models/model_svm.pkl --model_type svm
    deps:
      - src/models/train.py
      - ${processed_path}
    outs:
      - models/model_svm.pkl

  train_nb:
    cmd: python src/models/train.py --data ${processed_path} --out models/model_nb.pkl --model_type nb
    deps:
      - src/models/train.py
      - ${processed_path}
    outs:
      - models/model_nb.pkl

  train_rf:
    cmd: python src/models/train.py --data ${processed_path} --out models/model_rf.pkl --model_type rf
    deps:
      - src/models/train.py
      - ${processed_path}
    outs:
      - models/model_rf.pkl

  evaluate_all:
    cmd: python src/models/evaluate_all.py --models_dir models/ --data ${processed_path} --out reports/comparison.json
    deps:
      - models/model_logistic.pkl
      - models/model_svm.pkl
      - models/model_nb.pkl
      - models/model_rf.pkl
      - src/models/evaluate_all.py
    outs:
      - reports/comparison.json
